# H2
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

# PostgreSQL
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_SERVER}:5432/docker-k8s-db
    platform: postgresql
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # Hibernate ddl auto (none, create, create-drop, validate, update)